Repository brigadecore/brigade-cron-event-source, pull requests merged in 2022-03, with the labels that each got.

#45 Dockerfile: use gcr.io/distroless/static:nonroot as base for final stage
  Dockerfile
Labels: chore, security

#48 ci: push image to unstable repo
  .brigade/brigade.ts
  Makefile
Labels: security

#50 chore: brigade ts cleanup
  .brigade/brigade.ts
Labels: chore

#49 ci: scan image for vulnerabilities
  .brigade/brigade.ts
  .brigade/package.json
  .brigade/yarn.lock
  Makefile
Labels: security

#52 generate/publish sbom during release
  .brigade/brigade.ts
  Makefile
Labels: security

#55 release: sign image
  .brigade/brigade.ts
  Makefile
Labels: security
